- name: Create necessary directories
  delegate_to: localhost
  file: path={{item}} state=directory mode=0755
  with_items:
    - "{{ tempdir }}/filled/config/"
    - "{{ tempdir }}/filled/ssl/"

- name: Fill feedback.yml
  template: src={{ tempdir }}/feedback.yml.template dest={{ tempdir }}/filled/config/feedback.yml

- name: Copy ssl key
  local_action: copy src={{ conf_root }}/certs/{{ host }}/{{ apro_ssl_key }} dest={{ tempdir }}/filled/ssl/

- name: Copy ssl cert
  local_action: copy src={{ conf_root }}/certs/{{ host }}/{{ apro_ssl_cert }} dest={{ tempdir }}/filled/ssl/

- name: Create filled template tar
  local_action: shell tar -C {{ tempdir }}/filled/ -zvcf {{ tempdir }}/filled_templates.tgz .
  delegate_to: localhost
