---
  log:
    file: 'logs/feedback.log'
    level: info
  smtp:
    port: 8825
    host: localhost
  mail:
    to: to.address@mail.com
    from: from.address@mail.com
  ssl:
    feedback_host_cert_path: 'certs/'
    key_file: test.key
    cert_file: test.crt
